# Grafana Provisioning API 版本
apiVersion: 1

# 定義需要被自動配置的數據源列表 (Jaeger 版本)
datasources:
  # 數據源一：我們的核心 Prometheus
  - name: Prometheus-Main
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # =================================================================
  # == 數據源二：Loki-Main (日誌之眼) v2.0 ==
  # =================================================================
  - name: Loki-Main
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: 'Tracing-Main'
          internalLink:
            datasourceUid: 'Tracing-Main'
            query: '${__value.raw}'

  # =================================================================
  # == 數據源三：統一追蹤數據源 (Jaeger 配置) ==
  # =================================================================
  - name: Tracing-Main
    uid: Tracing-Main
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: 'Loki-Main'
        tags: ['service.name', 'container']
        filterByLogLevel: 'info'